# Generated by Django 4.2.11 on 2024-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagesetting_delete_imagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='img/', verbose_name='Image'),
        ),
    ]
