# Generated by Django 4.2.11 on 2024-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_imagesetting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image'),
        ),
    ]
