# Generated by Django 4.2.11 on 2024-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Job Description'),
        ),
    ]
