# Generated by Django 4.2.11 on 2024-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_experience_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default='Present', null=True, verbose_name='End Date'),
        ),
    ]
