# Generated by Django 4.2.11 on 2024-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_about_created_date_remove_about_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_content',
        ),
        migrations.AddField(
            model_name='about',
            name='about_content_1',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='About Content 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_content_2',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='About Content 2'),
        ),
    ]
