# Generated by Django 4.2.11 on 2024-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_about_about_content_about_about_content_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_link', models.URLField()),
                ('project_description', models.TextField()),
                ('project_category', models.CharField(choices=[('education', 'Education'), ('research', 'R&D Researches'), ('licences', 'Licences & Certifications'), ('github', 'GitHub')], max_length=50)),
                ('data_groups', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
