# Generated by Django 4.2.11 on 2024-05-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Slug'),
        ),
    ]
