# Generated by Django 4.2.11 on 2024-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='Image'),
        ),
    ]
